title: MiniExtend
description: 一个为迷你世界脚本设计的Lua库
base: /MiniExtendDoc/
plugins:
  - '@vuepress/last-updated'
themeConfig:
  nav:
    - text: 指南
      link: /guide/
    - text: API参考
      link: /api/
  sidebar:
    - /guide/
    - /guide/starter
    - /guide/environment
    - title: MiniExtend API
      children:
        - /api/
        - /api/core
        - /api/log
        - /api/time
        - /api/object
        - /api/event
        - /api/ui
    - changelog
  nextLinks: true
  prevLinks: true
  repo: 0-0000/MiniExtend
  docsRepo: kaikaibenkai/MiniExtendDoc
  docsDir: src
  docsBranch: main
  editLinks: true
  editLinkText: 修改此页面