title: MiniExtend
description: 一个为迷你世界脚本设计的Lua库
plugins:
  - '@vuepress/last-updated'
themeConfig:
  nav:
    - text: 指南
      link: /guide/
    - text: API参考
      link: /api/
  sidebar:
    /guide/:
      - ./
      - environment
      - core
    /api/:
      - ./
      - title: API 详细介绍
        children:
          - console
          - object
          - event
          - time
          - ui
  nextLinks: true
  prevLinks: true
  repo: 0-0000/MiniExtend
  docsRepo: kaikaibenkai/MiniExtend
  docsDir: src
  docsBranch: main
  editLinks: true
  editLinkText: 修改此页面